### ISSUE TITLE
Bug: iss is always https on app launch for Provider EHR Launch

### ISSUE THREAD

**Issue by chafey** [smart-on-fhir/smart-launcher#26]
The following line changes the iss to always use https:

https://github.com/smart-on-fhir/smart-launcher/blob/2ec963612f6f09dff54b1364e6e23ae7de0d2e55/static/index.html#L918

This will cause the app launch to fail when running smart-launcher without SSL (e.g. in dev mode).  There is no need to change from http to https since smart-launcher is serving up the page and proxying requests.

NOTE - the logic for changing to https is not present for the "Test With Sample App" path, it just uses the openUrl

I am happy to submit a PR if desired, I am new to this project though so wanted to check first to see if I am missing something before doing so

**Comment by vlad-ignatov** [comment]
This has been "fixed" for quite a while now, but the real issue wasn't addressed. The problem was that sometimes people open the online sandbox on http but try to launch an app that uses https. Then, the app may refuse to execute some requests to an "insecure location". Now, we have a dedicated warning and button to switch to https if the user has entered an https launch url on launcher running on http:
![Screenshot_20210624_112846](https://user-images.githubusercontent.com/1119082/123291388-0d8c6680-d4e0-11eb-808b-a85c470ac064.png)
