### ISSUE TITLE
[FEATURE] SmartOnFHIR: Introspection Endpoint

### ISSUE THREAD

**Issue by dmhalejr** [smart-on-fhir/smart-launcher#29]
*As a* developer with a custom authentication layer *I want* the ability to leverage `/apis/fhir/.well-known/smart-configuration` *so that* I can handle additional authorization flows that may occur when integrating with multiple EHR environments

Reference:
http://www.hl7.org/fhir/smart-app-launch/conformance/index.html#using-well-known

**Comment by vlad-ignatov** [comment]
Hi @dmhalejr,

Before we do any additions, I would like to clarify why do you need the introspection endpoint?

We do not currently support introspection just because we have never had to. Our tokens are JWT and are easy to introspect without an introspection endpoint. AFAIK, such an endpoint is mostly useful in real life when you have a separate auth server which is not the case in this sandbox.

Also, we do have a well-known JSONs available at `{FHIRBaseUri}/.well-known/smart-configuration`.

With that said, adding an introspection endpoint shouldn't be hard. We just want to make sure we do need it.
