### ISSUE TITLE
jwt error with access token signed in RS256, JsonWebTokenError: invalid algorithm

### ISSUE THREAD

**Issue by vincenzodesario** [smart-on-fhir/smart-launcher#38]
Hi All, i'm having problem to authenticate with an access token signed with RS256 created by identityserver4. Checking the code seems that is only managed token signed with symmetric key, could you please tell me why? it's a limit that in my case because i have to use identityserver4 to authenticate my EHR system and FHIR server.

**Comment by vlad-ignatov** [comment]
It is not clear to me exactly what you are trying to do, but the signing algorithm doesn't really matter in this case matter. You cannot use tokens created elsewhere and expect them to be accepted by the launcher.

**Comment by vincenzodesario** [comment]
Hi Vlad, thanks for the answer, however i'm trying to use the smart-launcher as reverse-proxy to communicate with FHIR server.
In detail i would that my identity server have to generate the token and the smart app have to use this token to communicate with FHIR server, since i don't want change the FHIR server configuration/code, i would use the smart-launcher only as reverse-proxy. It is possibile that?

**Comment by vlad-ignatov** [comment]
Doesn't sound possible. If you do already have an auth server and a FHIR server, then you don't need the launcher.

Note that the launcher is only usable for testing and "fakes" a lot of things. It does not come with an auth server. Instead, it just assumes everybody is already registered and allows any client_ids to launch everything. That is probably not what you want. 

Otherwise, if you are OK with that fake auth, the launcher is designed to work as a proxy. It can sit in-front of on open FHIR server but that has only been tested with HAPI servers.
