### ISSUE TITLE
"tests" vs "test"

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/smart-launcher#55]
The repo has a top-level `tests` directory *and* a `test` directory. I think only `test` is being used (e.g., by scripts defined in package.json). Can "tests" be deleted?

**Comment by vlad-ignatov** [comment]
Sure. That is already done (kinda). Tests have changed a lot in v2 and v3 branches. The v2 branch is currently deployed as a trail run and if there are no issues it will be merged into master. v3 has your changes merged experimentally.

In other words, please use the `v2` branch instead of master for now.

**Comment by jmandel** [comment]
Perfect -- thanks for the clarification. Will focus on `v2`.
