### ISSUE TITLE
MedicationStatement endpoint never returns any Medication resources

### ISSUE THREAD

**Issue by migrow** [smart-on-fhir/smart-launcher#7]
When launching a SMART app from the launcher, trying to GET the /MedicationStatement endpoint never appears to return any actual Medication resources, even for patients who have medications listed. According to the documentation [here](http://docs.smarthealthit.org/Swift-FHIR/Classes/MedicationStatement.html), I would expect to get a collection of Medication resources for a patient if I hit that endpoint. No matter what patient I try or how many medications they have listed, this is always returned:
```
{
  "resourceType": "Bundle",
  "id": "5ef12489-213f-4afd-82d8-514507f546d4",
  "meta": {
    "lastUpdated": "2018-11-19T09:06:54.594-05:00"
  },
  "type": "searchset",
  "total": 0,
  "link": [
    {
      "relation": "self",
      "url": "https://launch.smarthealthit.org/v/r3/fhir/MedicationStatement?_format=application%2Fjson&patient=smart-1685497"
    }
  ]
}
```
Is GET /MedicationStatement not properly implemented or am I maybe doing something wrong?

**Comment by vlad-ignatov** [comment]
Late last night, while the server was being restored to its default state it ran out of disk space. Unfortunately, this left the data in such "incomplete" state. We are working on fixing the issue...

**Comment by vlad-ignatov** [comment]
The server issues should be fixed now. However, I was too busy fixing those and I didn't read carefully what your problem is.

The documentation that you re referring to is correct, but unfortunately that does not mean that there is data for each resource type. In this case, to find the patient medications, you can use `MedicationRequest` or `MedicationDispense`. 

Different FHIR servers may support different resources which makes some things (like working with medications) tricky in my experience. You can also take a look at some examples:

STU3 - https://github.com/smart-on-fhir/sample-apps-stu3/blob/master/medications/index.html
DSTU2 - https://github.com/smart-on-fhir/sample-apps/blob/master/medications/index.html
